spring:
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days